In [145]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import re
import nltk
from nltk.corpus import stopwords 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics.pairwise import cosine_similarity
import os
import joblib
import streamlit as st

In [146]:
# reading data
data = pd.read_csv("resume_dataset_2.csv")
data.head()

,Name,Email,Phone,University,Graduation_Year,Years_Experience,Job_Role,Skills,Resume_Text
0,Tara Gonzalez,deborah75@example.com,8.371518e+09,Jadavpur University,2018,3,Data Scientist,"Python, Machine Learning, NumPy, Scikit-learn,...",\n Name: Tara Gonzalez\n Email: ...
1,Jared Quinn,matthew65@example.com,4.016587e+09,Delhi University,2017,6,Data Scientist,"NumPy, Scikit-learn, Statistics, TensorFlow, M...",\n Name: Jared Quinn\n Email: ma...
2,Jane Woods,phyllis29@example.net,9.002601e+09,Mumbai University,2020,5,Data Scientist,"TensorFlow, Python, NumPy, Machine Learning, NLP",\n Name: Jane Woods\n Email: phy...
3,Julie Chambers,hwright@example.net,4.157821e+09,Jadavpur University,2017,0,Data Scientist,"Scikit-learn, Statistics, Data Visualization, ...",\n Name: Julie Chambers\n Email:...
4,Tonya Campbell,hmyers@example.com,1.087373e+09,BITS Pilani,2015,2,Data Scientist,"Python, NumPy, SQL, Statistics, Pandas",\n Name: Tonya Campbell\n Email:...

In [147]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 815 entries, 0 to 814
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              815 non-null    object
 1   Email             779 non-null    object
 2   Phone             779 non-null    float64
 3   University        779 non-null    object
 4   Graduation_Year   815 non-null    int64
 5   Years_Experience  815 non-null    int64
 6   Job_Role          815 non-null    object
 7   Skills            779 non-null    object
 8   Resume_Text       815 non-null    object
dtypes: float64(1), int64(2), object(6)
memory usage: 57.4+ KB

In [148]:
data.describe()

              Phone  Graduation_Year  Years_Experience
count  7.790000e+02       815.000000        815.000000
mean   4.815580e+09      2019.001227          4.089571
std    2.887972e+09         2.659413          2.442071
min    3.937791e+07      2015.000000          0.000000
25%    2.363896e+09      2017.000000          2.000000
50%    4.604395e+09      2019.000000          4.000000
75%    7.318987e+09      2021.000000          6.000000
max    9.990742e+09      2023.000000          8.000000

In [149]:
data.columns

Index(['Name', 'Email', 'Phone', 'University', 'Graduation_Year',
       'Years_Experience', 'Job_Role', 'Skills', 'Resume_Text'],
      dtype='object')

In [150]:
df = data[['Resume_Text', 'Skills', 'Years_Experience', 'Job_Role']]

In [151]:
data['combined_text'] = data['Resume_Text'] + " " + data['Skills']

In [152]:
data['Resume_Text'].value_counts()

Resume_Text
\n        Name: Natasha Turner\n        Email: jessicasellers@example.org\n        Phone: 5841465361\n\n        Education:\n        Bachelor's Degree from Anna University, 2015\n\n        Work Experience:\n        4 years of experience working as a Software Engineer.\n\n        Skills:\n        REST API, Kubernetes, Git, C++, Docker\n\n        Projects:\n        Worked on multiple industry-relevant projects demonstrating expertise in REST API, Kubernetes, Git.\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           3
\n        Name: Linda Stone\n        Email: glenn08@example.org\n        Phone: 2966150343\n\n        Education:\n        Bachelor's Degree from IIM Ahmedabad, 2018\n\n        Work Experience:\n        7 years of experience working as a Software Engineer.\n\n        Skills:\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         3
\n        Name: Kenneth Grant\n        Email: stephanie79@example.net\n        Phone: 2783029348\n\n        Education:\n        Bachelor's Degree from IIM Ahmedabad, 2021\n\n        Work Experience:\n        6 years of experience working                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                3
\n        Name: Heather Miranda\n        Email: alvarezalicia@example.com\n        Phone: 8183790777\n\n        Education:\n        Bachelor's Degree from Anna University, 2023\n\n        Work Experience:\n        3 years of experience working as a Software Engineer.\n\n        Skills:\n        Kubernetes, Docker, Python, REST API, Java\n\n        Projects:\n        Worked on multiple industry-relevant projects demonstrating expertise in Kubernetes, Docker, Python.\n         Results-driven professional with analytical mindset.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         3
\n        Name: Kenneth Grant\n        Email: stephanie79@example.net\n        Phone: 2783029348\n\n        Education:\n        Bachelor's Degree from IIM Ahmedabad, 2021\n\n        Work Experience:\n        6 years of experience working as a Software Engineer.\n\n        Skills:\n        C++, Kubernetes, Java, Git, Docker\n\n        Projects:\n        Worked on multiple industry-relevant projects demonstrating expertise in C++, Kubernetes, Java.\n         Results-driven professional with analytical mindset. \n        Name: Kenneth Grant\n        Email: stephanie79@example.net\n        Phone: 2783029348\n\n        Education:\n        Bachelor's Degree from IIM Ahmedabad, 2021\n\n        Work Experience:\n        6 years of experience working as a Software Engineer.\n\n        Skills:\n        C++, Kubernetes, Java, Git, Docker\n\n        Projects:\n        Worked on multiple industry-relevant projects demonstrating expertise in C++, Kubernetes, Java.\n         Results-driven professional with analytical mindset.                                                                                                                                          2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ..
\n        Name: Joanne Schmidt\n        Email: vwoods@example.com\n        Phone: 3630639057\n\n        Education:\n        Bachelor's Degree from IIM Ahmedabad, 2016\n\n        Work Experience:\n        4 years of experience working as a Software Engineer.\n\n        Skills:\n        OOP, Microservices, Python, C++, REST API\n\n        Projects:\n        Worked on multiple industry-relevant projects demonstrating expertise in OOP, Microservices, Python.\n         Experienced in leadership and cross-functional collaboration. Combined analytics and marketing responsibilities \n        Name: Joanne Schmidt\n        Email: vwoods@example.com\n        Phone: 3630639057\n\n        Education:\n        Bachelor's Degree from IIM Ahmedabad, 2016\n\n        Work Experience:\n        4 years of experience working as a Software Engineer.\n\n        Skills:\n        OOP, Microservices, Python, C++, REST API\n\n        Projects:\n        Worked on multiple industry-relevant projects demonstrating expertise in OOP, Microservices, Python.\n         Experienced in leadership and cross-functional collaboration. Combined analytics and marketing responsibilities    1
\n        Name: Jeffrey Gonzalez\n        Email: clarkesteven@example.org\n        Phone: 6040422223\n\n        Education:\n        Bachelor's Degree from IIM Ahmedabad, 2016\n\n        Work Experience:\n        5 years of experience working as a Software Engineer.\n\n        Skills:\n        C++, Microservices, Docker, Spring Boot, REST API\n\n        Projects:\n        Worked on multiple industry-relevant projects demonstrating expertise in C++, Microservices, Docker.\n         miscellaneous experience Bridged software engineering and business operations \n        Name: Jeffrey Gonzalez\n        Email: clarkesteven@example.org\n        Phone: 6040422223\n\n        Education:\n        Bachelor's Degree from IIM Ahmedabad, 2016\n\n        Work Experience:\n        5 years of experience working as a Software Engineer.\n\n        Skills:\n        C++, Microservices, Docker, Spring Boot, REST API\n\n        Projects:\n        Worked on multiple industry-relevant projects demonstrating expertise in C++, Microservices, Docker.\n         miscellaneous experience Bridged software engineering and business operations                                        1
\n        Name: Stacy SmitH\n        Email: michellewong@exampLe.org\n        PhoNe: 1702717101\n\n        EducatiOn:\n        BacheloR's Degree from Jadavpur University, 2021\n\n        Work Experience:\n        5 years of experiENcE working as a SOftWare EngineEr.\n\n        Skills:\n        Java, C++, Spring Boot, OOP, REST API\n\n        ProjeCts:\n        WoRked oN muLtiple industry-relevant projects demonstrAtinG ExpeRtisE in Java, C++, SprinG BOot.\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
\n        Name: Bryan Chapman\n        Email: jonesthomas@example.net\n        Phone: 5183461251\n\n        Education:\n        Bachelor's Degree from Mumbai University, 2018\n\n        Work Experience:\n        2 years of experience working as a Software Engineer.\n\n        Skills:\n        Spring Boot, C++, Docker, Python, Git\n\n        Projects:\n        Worked on multiple industry-relevant projects demonstrating expertise in Spring Boot, C++, Docker.\n         Experienced in leadership and cross-functional collaboration. Worked in cross-domain tech-finance environment                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
\n        Name: Jane Woods\n        Email: phyllis29@example.net\n        Phone: 9002600720\n\n        Education:\n        Bachelor's Degree from Mumbai University, 2020\n\n        Work Experience:\n        5 years of experience working as a  Scientist.\n\n        Skills:\n        TensorFlow, Python, NumPy, Machine Learning, NLP\n\n        Projects:\n        Worked on multiple industry-relevant projects demonstrating expertise in TensorFlow, Python, NumPy.\n         Proficient in project management and stakeholder coordination.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Name: count, Length: 767, dtype: int64

In [153]:
# preprocessing data
stop_words = set(stopwords.words('english'))
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

data['Cleaned'] = data['Resume_Text'].apply(clean_text)

C:\Users\Shubham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\nltk\corpus\reader\api.py:218: RuntimeWarning: Security Violation [CorpusReader]: Unauthorized path C:\Users\Shubham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\Roaming\nltk_data\corpora\stopwords\english
  with self.open(f) as fp:
C:\Users\Shubham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\nltk\data.py:388: RuntimeWarning: Security Violation [pathsec.open]: Unauthorized path C:\Users\Shubham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\Roaming\nltk_data\corpora\stopwords\english
  stream = _secure_open(self._path, "rb")

In [154]:
data.head()

,Name,Email,Phone,University,Graduation_Year,Years_Experience,Job_Role,Skills,Resume_Text,combined_text,Cleaned
0,Tara Gonzalez,deborah75@example.com,8.371518e+09,Jadavpur University,2018,3,Data Scientist,"Python, Machine Learning, NumPy, Scikit-learn,...",\n Name: Tara Gonzalez\n Email: ...,\n Name: Tara Gonzalez\n Email: ...,name tara gonzalez email deborah example com p...
1,Jared Quinn,matthew65@example.com,4.016587e+09,Delhi University,2017,6,Data Scientist,"NumPy, Scikit-learn, Statistics, TensorFlow, M...",\n Name: Jared Quinn\n Email: ma...,\n Name: Jared Quinn\n Email: ma...,name jared quinn email matthew example com pho...
2,Jane Woods,phyllis29@example.net,9.002601e+09,Mumbai University,2020,5,Data Scientist,"TensorFlow, Python, NumPy, Machine Learning, NLP",\n Name: Jane Woods\n Email: phy...,\n Name: Jane Woods\n Email: phy...,name jane woods email phyllis example net phon...
3,Julie Chambers,hwright@example.net,4.157821e+09,Jadavpur University,2017,0,Data Scientist,"Scikit-learn, Statistics, Data Visualization, ...",\n Name: Julie Chambers\n Email:...,\n Name: Julie Chambers\n Email:...,name julie chambers email hwright example net ...
4,Tonya Campbell,hmyers@example.com,1.087373e+09,BITS Pilani,2015,2,Data Scientist,"Python, NumPy, SQL, Statistics, Pandas",\n Name: Tonya Campbell\n Email:...,\n Name: Tonya Campbell\n Email:...,name tonya campbell email hmyers example com p...

In [155]:
data['Cleaned'].value_counts()

Cleaned
name linda stone email glenn example org phone education bachelor degree iim ahmedabad work experience years experience working software engineer skills                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               4
name natasha turner email jessicasellers example org phone education bachelor degree anna university work experience years experience working software engineer skills rest api kubernetes git c docker projects worked multiple industry relevant projects demonstrating expertise rest api kubernetes git                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            3
name kenneth grant email stephanie example net phone education bachelor degree iim ahmedabad work experience years experience working                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  3
name heather miranda email alvarezalicia example com phone education bachelor degree anna university work experience years experience working software engineer skills kubernetes docker python rest api java projects worked multiple industry relevant projects demonstrating expertise kubernetes docker python results driven professional analytical mindset                                                                                                                                                                                                                                                                                                                                                                                                                                                      3
name sean holloway email estespatrick example org phone education bachelor degree delhi university work experience years experience working software engineer skills git rest api oop java kubernetes projects worked multiple industry relevant projects demonstrating expertise git rest api oop                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ..
name joanne schmidt email vwoods example com phone education bachelor degree iim ahmedabad work experience years experience working software engineer skills oop microservices python c rest api projects worked multiple industry relevant projects demonstrating expertise oop microservices python experienced leadership cross functional collaboration combined analytics marketing responsibilities name joanne schmidt email vwoods example com phone education bachelor degree iim ahmedabad work experience years experience working software engineer skills oop microservices python c rest api projects worked multiple industry relevant projects demonstrating expertise oop microservices python experienced leadership cross functional collaboration combined analytics marketing responsibilities    1
name jeffrey gonzalez email clarkesteven example org phone education bachelor degree iim ahmedabad work experience years experience working software engineer skills c microservices docker spring boot rest api projects worked multiple industry relevant projects demonstrating expertise c microservices docker miscellaneous experience bridged software engineering business operations name jeffrey gonzalez email clarkesteven example org phone education bachelor degree iim ahmedabad work experience years experience working software engineer skills c microservices docker spring boot rest api projects worked multiple industry relevant projects demonstrating expertise c microservices docker miscellaneous experience bridged software engineering business operations                            1
name stacy smith email michellewong example org phone education bachelor degree jadavpur university work experience years experience working software engineer skills java c spring boot oop rest api projects worked multiple industry relevant projects demonstrating expertise java c spring boot                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   1
name bryan chapman email jonesthomas example net phone education bachelor degree mumbai university work experience years experience working software engineer skills spring boot c docker python git projects worked multiple industry relevant projects demonstrating expertise spring boot c docker experienced leadership cross functional collaboration worked cross domain tech finance environment                                                                                                                                                                                                                                                                                                                                                                                                               1
name jason ford email uprice example org phone education bachelor degree delhi university work experience years experience working scientist skills machine learning sql tensorflow statistics projects worked multiple industry relevant projects demonstrating expertise machine learning sql                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1
Name: count, Length: 760, dtype: int64

In [156]:
tfidf = TfidfVectorizer()
text_features = tfidf.fit_transform(data['Cleaned']).toarray()

In [157]:
# Adding experiance feature 
exp = data['Years_Experience'].values.reshape(-1, 1)
X = np.hstack((text_features, exp))
Y = data['Job_Role'].values

In [158]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler(with_mean=False)  # TF-IDF ke liye important
X = scaler.fit_transform(X)

In [159]:
# train-test split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [160]:
# KNN model
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, Y_train)

KNeighborsClassifier()

In [161]:
# Naive Bayes 
nb = MultinomialNB()
nb.fit(X_train, Y_train)

MultinomialNB()

In [162]:
svm = SVC(kernel='linear')
svm.fit(X_train, Y_train)

SVC(kernel='linear')

In [163]:
# Neural networks
nn = MLPClassifier(hidden_layer_sizes=(100,50), max_iter=500)
nn.fit(X_train, Y_train)

MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=500)

In [164]:
model = {"KNN": knn, "Naive Bayes": nb, "SVM": svm, "Neural Network": nn}

for name , mdl in model.items():
    Y_pred = mdl.predict(X_test)
    print(f"{name} Accuracy:", accuracy_score(Y_test, Y_pred))
    print(f'{name} Classification Report :', classification_report(Y_test, Y_pred))
    print(f'{name} Confusion Matrix :', confusion_matrix(Y_test, Y_pred))

KNN Accuracy: 0.4171779141104294
KNN Classification Report :                    precision    recall  f1-score   support

   Data Scientist       0.00      0.00      0.00        30
Financial Analyst       0.00      0.00      0.00        16
     HR Executive       0.33      0.04      0.07        26
Marketing Manager       0.00      0.00      0.00        23
Software Engineer       0.42      0.99      0.59        68

         accuracy                           0.42       163
        macro avg       0.15      0.20      0.13       163
     weighted avg       0.23      0.42      0.26       163

KNN Confusion Matrix : [[ 0  0  1  0 29]
 [ 0  0  1  0 15]
 [ 0  0  1  0 25]
 [ 0  0  0  0 23]
 [ 0  0  0  1 67]]
Naive Bayes Accuracy: 0.7116564417177914
Naive Bayes Classification Report :                    precision    recall  f1-score   support

   Data Scientist       0.65      0.50      0.57        30
Financial Analyst       0.52      0.81      0.63        16
     HR Executive       0.67      0.62      0.64        26
Marketing Manager       0.61      0.61      0.61        23
Software Engineer       0.85      0.85      0.85        68

         accuracy                           0.71       163
        macro avg       0.66      0.68      0.66       163
     weighted avg       0.72      0.71      0.71       163

Naive Bayes Confusion Matrix : [[15  3  6  2  4]
 [ 1 13  0  1  1]
 [ 3  1 16  2  4]
 [ 2  4  2 14  1]
 [ 2  4  0  4 58]]
SVM Accuracy: 0.3987730061349693
SVM Classification Report :                    precision    recall  f1-score   support

   Data Scientist       0.25      0.13      0.17        30
Financial Analyst       0.29      0.50      0.36        16
     HR Executive       0.52      0.54      0.53        26
Marketing Manager       0.36      0.17      0.24        23
Software Engineer       0.43      0.51      0.47        68

         accuracy                           0.40       163
        macro avg       0.37      0.37      0.35       163
     weighted avg       0.39      0.40      0.38       163

SVM Confusion Matrix : [[ 4  5  2  2 17]
 [ 1  8  1  1  5]
 [ 2  0 14  0 10]
 [ 0  2  3  4 14]
 [ 9 13  7  4 35]]
Neural Network Accuracy: 0.5766871165644172
Neural Network Classification Report :                    precision    recall  f1-score   support

   Data Scientist       0.50      0.40      0.44        30
Financial Analyst       0.33      0.38      0.35        16
     HR Executive       0.57      0.65      0.61        26
Marketing Manager       0.56      0.43      0.49        23
Software Engineer       0.67      0.72      0.70        68

         accuracy                           0.58       163
        macro avg       0.53      0.52      0.52       163
     weighted avg       0.57      0.58      0.57       163

Neural Network Confusion Matrix : [[12  2  4  2 10]
 [ 2  6  4  1  3]
 [ 3  0 17  0  6]
 [ 2  2  4 10  5]
 [ 5  8  1  5 49]]

C:\Users\Shubham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Shubham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Shubham\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [165]:
os.makedirs("models", exist_ok=True)
joblib.dump(knn, "models/knn.pkl")
joblib.dump(nb, "models/nb.pkl")
joblib.dump(svm, "models/svm.pkl")
joblib.dump(nn, "models/nn.pkl")
joblib.dump(tfidf, "models/tfidf.pkl")

['models/tfidf.pkl']

In [166]:
if 	data['Years_Experience'].iloc[0]> 2:
    print("Shortlisted")
else:
    print("Rejected")

Shortlisted

In [167]:
best_model = max(model.items(), key=lambda x: accuracy_score(Y_test, x[1].predict(X_test)))
print("Best Model:", best_model[0])

Best Model: Naive Bayes

In [168]:
# job_description = "Looking for a data scientist with experience in machine learning and Python."
# jb_vec = tfidf.transform([job_description])
# resume_vec = tfidf.transform([data['Cleaned'][0]])
# Score = cosine_similarity(jb_vec, resume_vec)
# print("Resume Score:", Score[0][0])

In [169]:
def get_top_candidates(jd, top_n=5):
    jd_vec = tfidf.transform([jd])
    resume_vecs = tfidf.transform(data['Cleaned'])
    
    scores = cosine_similarity(jd_vec, resume_vecs)[0]
    
    top_idx = scores.argsort()[-top_n:][::-1]
    
    results = data.iloc[top_idx][['Name', 'Job_Role', 'Skills', 'Years_Experience']]
    results['Match_Score'] = scores[top_idx]
    
    return results

In [170]:
jd = input("Enter Job Description: ")
results = get_top_candidates(jd)

for i, row in results.iterrows():
    print(f"""
Name: {row['Name']}
Role: {row['Job_Role']}
Experience: {row['Years_Experience']} years
Match Score: {row['Match_Score']:.2f}
Skills: {row['Skills']}
\n
""")
    
print(results)

Name: Jason Cox
Role: Financial Analyst
Experience: 2 years
Match Score: 0.00
Skills: Git, REST API, Spring Boot, Java, C++




Name: Bryan Chapman
Role: Software Engineer
Experience: 2 years
Match Score: 0.00
Skills: nan




Name: Stacy Smith
Role: Marketing Manager
Experience: 5 years
Match Score: 0.00
Skills: Java, C++, Spring Boot, OOP, REST API




Name: Ann White
Role: Software Engineer
Experience: 7 years
Match Score: 0.00
Skills: OOP, Microservices, Python, Git, Kubernetes




Name: Jeffrey Gonzalez
Role: Software Engineer
Experience: 5 years
Match Score: 0.00
Skills: C++, Microservices, Docker, Spring Boot, REST API



                 Name           Job_Role  \
814         Jason Cox  Financial Analyst
813     Bryan Chapman  Software Engineer
812       Stacy Smith  Marketing Manager
811         Ann White  Software Engineer
810  Jeffrey Gonzalez  Software Engineer

                                                Skills  Years_Experience  \
814              Git, REST API, Spring Boot, Java, C++                 2
813                                                NaN                 2
812              Java, C++, Spring Boot, OOP, REST API                 5
811        OOP, Microservices, Python, Git, Kubernetes                 7
810  C++, Microservices, Docker, Spring Boot, REST API                 5

     Match_Score
814          0.0
813          0.0
812          0.0
811          0.0
810          0.0

In [171]:
for i, row in results.iterrows():
    print(f"""
Name: {row['Name']}
Role: {row['Job_Role']}
Experience: {row['Years_Experience']} years
Match Score: {row['Match_Score']:.2f}
Skills: {row['Skills']}
---------------------------
""")

Name: Jason Cox
Role: Financial Analyst
Experience: 2 years
Match Score: 0.00
Skills: Git, REST API, Spring Boot, Java, C++
---------------------------


Name: Bryan Chapman
Role: Software Engineer
Experience: 2 years
Match Score: 0.00
Skills: nan
---------------------------


Name: Stacy Smith
Role: Marketing Manager
Experience: 5 years
Match Score: 0.00
Skills: Java, C++, Spring Boot, OOP, REST API
---------------------------


Name: Ann White
Role: Software Engineer
Experience: 7 years
Match Score: 0.00
Skills: OOP, Microservices, Python, Git, Kubernetes
---------------------------


Name: Jeffrey Gonzalez
Role: Software Engineer
Experience: 5 years
Match Score: 0.00
Skills: C++, Microservices, Docker, Spring Boot, REST API
---------------------------